---
title: "hw3"
author: "Si Chen"
date: "September 27, 2018"
output: html_document
---
```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
require(RColorBrewer)
```

## Points\lines\polygons from GEOJSON

```{r}
#input GEOJSON data
bridge <- readOGR("http://openac-alcogis.opendata.arcgis.com/datasets/65e21a4d53b9419b9c422657cac63a1b_0.geojson")
cemetry <- readOGR("http://openac-alcogis.opendata.arcgis.com/datasets/4d83e90db45e48a688376c431ceec81f_0.geojson")
snowroute <- readOGR("https://opendata.arcgis.com/datasets/4c7c1a0184d94ca0a0341c0eef66eb80_1.geojson")
```

## specify colors
```{r}
#specify the color
palpolygon <- colorNumeric(
  palette = "RdYlBu",
  domain= cemetry$PERIMETER)
palpoints <- colorFactor(c("green"), domain = bridge$BRBIDGE_NA)
```
## basemap
```{r}
PitMap <- leaflet() %>%
  addProviderTiles("OpenStreetMap.BlackAndWhite", group =" Street",options = providerTileOptions(noWrap = TRUE)) %>%
  addProviderTiles("Stamen.Toner", group="Toner",options = providerTileOptions(noWrap = TRUE)) %>%
  setView(-80,40.5,zoom=10)%>%
  #add three layers 
  addCircleMarkers(data=bridge,radius=6,color=~palpoints(bridge$BRBIDGE_NA),stroke=FALSE,fillOpacity = 0.5,group="bridge") %>%
  addPolylines(data=snowroute,color="black",weight=2,group="snowroute") %>%
  addPolygons(data = cemetry, color = ~palpolygon(PERIMETER),group="cemetry") %>%
  #add legend for polgon layer
  addLegend("bottomright", pal = palpolygon, values = cemetry$PERIMETER,
            title = "Cemetry Perimeter(meters)",
            opacity = 1
            ) %>%
  #add layers control
    addLayersControl(
    baseGroups = c("Street", "Toner"),
    overlayGroups = c("bridge","snowroute","cemetry"),
                     options = layersControlOptions(collapsed = FALSE))
PitMap
``` 
